#!/bin/bash

echo "---------------------------------"
echo "Regression Tests for Enc2MusicXML"
echo "---------------------------------"
echo

testcount=0
failures=0

rwtest() {
      echo -n "testing $2 $3";
      REF=$2.ref.$3
      RES=$2.out.$3
      SRC=$2.enc
      $1 -$4 $SRC >$RES 2> /dev/null
      if diff -q $REF $RES &> /dev/null; then
            echo -e "\r\t\t\t\t\t\t...OK";
      else
            echo -e "\r\t\t\t\t\t\t...FAILED";
            failures=$(($failures+1));
            echo "+++++++++DIFF++++++++++++++"
            diff $REF $RES
            echo "+++++++++++++++++++++++++++"
      fi
      #rm $RES
      testcount=$(($testcount+1))
      }

rwtestAll() {
      for f in `ls *.enc | sort`; do
            NAME=`basename $f .enc`
            rwtest $1 $NAME txt d
            if [ -e $NAME.ref.xml ]
            then
                  rwtest $1 $NAME xml m
            fi
      done
      }

usage() {
      echo "usage: $0 <path to Enc2MusicXML>"
      echo
      exit 1
      }

if [ $# -eq 1 ]; then
      rwtestAll $1
else
      usage
fi

echo
echo "$testcount test(s), $failures failure(s)"
